import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import AppShell from "../components/AppShell";
import { createTrip } from "../api/trips";

export default function CreateTripPage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ name: "", startDate: "", endDate: "", description: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  async function submit(event) { event.preventDefault(); setError(""); if (!form.name.trim() || !form.startDate || !form.endDate) return setError("Give your journey a name and choose its dates."); if (form.endDate < form.startDate) return setError("Your return date needs to come after your departure."); setSaving(true); try { const trip = await createTrip(form); navigate(`/trips/${trip.id}`); } catch (err) { setError(err.message || "We couldn't create your trip just yet."); setSaving(false); } }
  return <AppShell><p className="eyebrow">New itinerary</p><h1 className="display">Where to next?</h1><p className="lede">Begin with the shape of your escape. You can add cities and favourite experiences once the journey is on the map.</p><div className="form-layout"><form onSubmit={submit} className="form-card"><h2>Trip essentials</h2><label className="field">Name your journey<input autoFocus name="name" value={form.name} onChange={change} placeholder="e.g. A week under Italian skies" /></label><div className="two-fields"><label className="field">Departure<input type="date" name="startDate" value={form.startDate} onChange={change} /></label><label className="field">Return<input type="date" name="endDate" min={form.startDate || undefined} value={form.endDate} onChange={change} /></label></div><label className="field">A note for future you <span style={{ color: "#8b9690", fontWeight: 400 }}>(optional)</span><textarea name="description" value={form.description} onChange={change} placeholder="What are you hoping to discover?" /></label>{error && <div className="alert">{error}</div>}<div className="form-actions"><button className="primary" disabled={saving}>{saving ? "Creating your trip…" : "Create trip"} <span>→</span></button><Link className="secondary" to="/trips">Maybe later</Link></div></form><aside className="form-aside"><div className="map-art"><span>The world<br />is yours.</span></div><div className="tip"><h3><b>01</b>Keep it loose</h3><p>A first draft is enough. The best itineraries have space to breathe.</p></div><div className="tip"><h3><b>02</b>Make it yours</h3><p>Add cities, experiences, and a budget after you begin.</p></div></aside></div></AppShell>;
}
