import { useState } from 'react';
import { createTrip } from '../api/trips';

const today = new Date().toISOString().slice(0, 10);
export default function CreateTripPage({ ownerId, navigate }) {
  const [form, setForm] = useState({ name: '', start_date: today, end_date: today, description: '', cover_image_url: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const set = (key, value) => setForm({ ...form, [key]: value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const trip = await createTrip({ ...form, owner_id: ownerId, description: form.description || undefined, cover_image_url: form.cover_image_url || undefined }); navigate(`/trips/${trip.id}`); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  return <main className="page narrow"><button className="back" onClick={() => navigate('/dashboard')}>← My trips</button><span className="eyebrow">NEW JOURNEY</span><h1>Let’s make it official.</h1><p className="lead">Start with the broad strokes. You can add every destination and day next.</p><form className="panel form-grid" onSubmit={submit}><label>Trip name<input required placeholder="e.g. A perfect week in Japan" value={form.name} onChange={(e) => set('name', e.target.value)} /></label><div className="two-col"><label>Start date<input required type="date" value={form.start_date} onChange={(e) => set('start_date', e.target.value)} /></label><label>End date<input required type="date" min={form.start_date} value={form.end_date} onChange={(e) => set('end_date', e.target.value)} /></label></div><label>Tell us about this trip <span className="muted">(optional)</span><textarea placeholder="The pace, the feeling, the must-dos…" value={form.description} onChange={(e) => set('description', e.target.value)} /></label><label>Cover photo URL <span className="muted">(optional)</span><input type="url" placeholder="https://…" value={form.cover_image_url} onChange={(e) => set('cover_image_url', e.target.value)} /></label>{error && <p className="alert">{error}</p>}<button className="button" disabled={saving}>{saving ? 'Creating…' : 'Create trip →'}</button></form></main>;
}
