import { useEffect, useMemo, useState } from 'react';
import { listCities, listStops, listTrips } from '../api/trips';

const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value || 0);
const stateOf = (trip) => { const today = new Date().toISOString().slice(0, 10); return trip.end_date < today ? 'Completed' : trip.start_date > today ? 'Upcoming' : 'Ongoing'; };

export default function DashboardPage({ ownerId, navigate }) {
  const [trips, setTrips] = useState([]); const [cities, setCities] = useState([]); const [tab, setTab] = useState('Ongoing'); const [stops, setStops] = useState({}); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([listTrips(ownerId), listCities()]).then(([t, c]) => { setTrips(t); setCities(c); return Promise.all(t.map((trip) => listStops(trip.id).then((value) => [trip.id, value]))); }).then((entries) => setStops(Object.fromEntries(entries))).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [ownerId]);
  const visible = useMemo(() => trips.filter((trip) => stateOf(trip) === tab), [trips, tab]);
  return <main className="page"><section className="hero"><div><span className="eyebrow">TRIP DASHBOARD</span><h1>Where will you go next?</h1><p>Keep every part of your journey in one calm, clear place.</p></div><button className="button" onClick={() => navigate('/create')}>+ Plan new trip</button></section>{error && <p className="alert">Couldn’t load dashboard: {error}</p>}<section><div className="section-heading"><h2>My trips</h2><div className="tabs">{['Ongoing', 'Upcoming', 'Completed'].map((name) => <button key={name} className={tab === name ? 'active' : ''} onClick={() => setTab(name)}>{name}</button>)}</div></div>{loading ? <p>Loading your journeys…</p> : visible.length ? <div className="trip-grid">{visible.map((trip) => <article className="trip-card" key={trip.id} onClick={() => navigate(`/trips/${trip.id}`)}><div className="card-art" style={trip.cover_image_url ? { backgroundImage: `url(${trip.cover_image_url})` } : {}}><span>{stateOf(trip)}</span></div><div className="trip-card-body"><h3>{trip.name}</h3><p>{trip.start_date} — {trip.end_date}</p><div><span>{stops[trip.id]?.length || 0} sections</span><strong>{money(trip.total_budget)}</strong></div></div></article>)}</div> : <div className="empty"><h3>No {tab.toLowerCase()} trips yet</h3><p>Your next map pin is waiting.</p><button className="button" onClick={() => navigate('/create')}>Start planning</button></div>}</section><section className="destination-section"><div className="section-heading"><h2>Recommended destinations</h2><span className="muted">Picked from popular places</span></div><div className="destination-grid">{cities.slice().sort((a, b) => (b.popularity || 0) - (a.popularity || 0)).slice(0, 4).map((city) => <article className="destination-card" key={city.id} style={city.image_url ? { backgroundImage: `linear-gradient(0deg, rgba(6,30,23,.8), transparent), url(${city.image_url})` } : {}}><h3>{city.name}</h3><p>{city.country}</p></article>)}</div></section></main>;
}
