import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import AppShell from "../components/AppShell";
import { deleteTrip, getTrip, updateTrip } from "../api/trips";
import { getDraft, saveDraft } from "../lib/drafts";

const cities = ["Paris, France", "Tokyo, Japan", "Rome, Italy", "Lisbon, Portugal", "Bali, Indonesia", "New York, USA", "Bangkok, Thailand", "Reykjavík, Iceland"];

export default function TripBuilderPage() {
  const { tripId } = useParams(); const navigate = useNavigate(); const [trip, setTrip] = useState(null); const [draft, setDraft] = useState({ stops: [], notes: "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showStop, setShowStop] = useState(false); const [activityStop, setActivityStop] = useState(null); const [editing, setEditing] = useState(false);
  useEffect(() => { async function load() { setLoading(true); setError(""); try { setTrip(await getTrip(tripId)); setDraft(getDraft(tripId)); } catch (err) { setError(err.status === 404 ? "This journey doesn't exist or was deleted." : "We couldn't load this journey."); } finally { setLoading(false); } } load(); }, [tripId]);
  function updateDraft(next) { setDraft(next); saveDraft(tripId, next); }
  const spend = useMemo(() => draft.stops.reduce((total, stop) => total + Number(stop.budget || 0) + stop.activities.reduce((sum, item) => sum + Number(item.cost || 0), 0), 0), [draft]);
  async function removeTrip() { if (!window.confirm(`Delete “${trip.name}”? This cannot be undone.`)) return; try { await deleteTrip(tripId); localStorage.removeItem(`globetrotter-trip-draft:${tripId}`); navigate("/trips"); } catch (err) { window.alert(err.message || "Could not delete this trip."); } }
  async function saveTrip(updates) { const updated = await updateTrip(tripId, updates); setTrip(updated); setEditing(false); }
  function addStop(stop) { updateDraft({ ...draft, stops: [...draft.stops, { ...stop, id: crypto.randomUUID(), activities: [] }] }); setShowStop(false); }
  function removeStop(id) { updateDraft({ ...draft, stops: draft.stops.filter((stop) => stop.id !== id) }); }
  function addActivity(stopId, activity) { updateDraft({ ...draft, stops: draft.stops.map((stop) => stop.id === stopId ? { ...stop, activities: [...stop.activities, { ...activity, id: crypto.randomUUID() }] } : stop) }); setActivityStop(null); }
  function removeActivity(stopId, activityId) { updateDraft({ ...draft, stops: draft.stops.map((stop) => stop.id === stopId ? { ...stop, activities: stop.activities.filter((activity) => activity.id !== activityId) } : stop) }); }
  if (loading) return <AppShell wide><div className="loading">Building your itinerary</div></AppShell>;
  if (error || !trip) return <AppShell><section className="empty"><div className="empty-mark">!</div><h2>That route got away from us.</h2><p>{error || "This journey is unavailable."}</p><Link className="primary" to="/trips">Back to journeys</Link></section></AppShell>;
  return <AppShell wide><section className="trip-top"><div><Link to="/trips" className="crumb">My journeys&nbsp; / &nbsp;Itinerary</Link>{editing ? <TripEditor trip={trip} onSave={saveTrip} onCancel={() => setEditing(false)} /> : <><div className="trip-title"><h1 className="display">{trip.name}</h1><span className="tag">{trip.is_public ? "Shared trip" : "Private journey"}</span></div><p className="trip-description">{fullDate(trip.start_date)} — {fullDate(trip.end_date)} · {trip.description || "A path made for wandering."}</p></>}</div>{!editing && <div className="trip-top-actions"><button className="secondary" onClick={() => setEditing(true)}>Edit trip</button><button className="icon-btn" onClick={removeTrip} aria-label="Delete trip">⌫</button></div>}</section><section className="trip-layout"><div className="route-panel"><div className="route-heading"><h2>Your route</h2><button className="primary" onClick={() => setShowStop(true)}>+ Add a stop</button></div>{draft.stops.length ? draft.stops.map((stop, index) => <Stop key={stop.id} stop={stop} index={index} onDelete={() => removeStop(stop.id)} onAdd={() => setActivityStop(stop)} onRemoveActivity={(activityId) => removeActivity(stop.id, activityId)} />) : <div className="route-empty"><h3>Drop your first pin.</h3><p>Choose a city to begin shaping your route.</p><button className="primary" onClick={() => setShowStop(true)}>Add a city</button></div>}</div><aside className="sidebar"><div className="summary"><h3>Trip at a glance</h3><div className="summary-row"><span>Stops</span><strong>{draft.stops.length} {draft.stops.length === 1 ? "city" : "cities"}</strong></div><div className="summary-row"><span>Experiences</span><strong>{draft.stops.reduce((sum, stop) => sum + stop.activities.length, 0)}</strong></div><div className="summary-row"><span>Planned spend</span><strong>{money(spend)}</strong></div></div><div className="side-callout"><h3>Make it yours.</h3><p>Your route draft is saved securely in this browser while you explore ideas.</p><button className="primary" disabled={!draft.stops.length} onClick={() => draft.stops.length && setActivityStop(draft.stops[0])}>Add an experience <span>→</span></button></div></aside></section>{showStop && <StopModal trip={trip} onClose={() => setShowStop(false)} onSave={addStop} />}{activityStop && <ActivityModal city={activityStop.city} onClose={() => setActivityStop(null)} onSave={(activity) => addActivity(activityStop.id, activity)} />}</AppShell>;
}

function Stop({ stop, index, onDelete, onAdd, onRemoveActivity }) { const [place, country = ""] = stop.city.split(", "); return <article className="stop"><div className="stop-rail"><span className="stop-number">{String(index + 1).padStart(2, "0")}</span></div><div><div className="stop-head"><div><h3>{place}</h3><small>{country || "Destination"}</small></div><div className="stop-meta"><span className="pill">{money(stop.budget)} est.</span><button className="remove" onClick={onDelete}>Remove</button></div></div><p className="stop-date">{fullDate(stop.startDate)} — {fullDate(stop.endDate)}</p><ul className="activities">{stop.activities.map((activity) => <li key={activity.id}><span className="time">{activity.time || "Anytime"}</span><span className="name">{activity.name}</span><span className="cost">{money(activity.cost)}</span><button className="remove" onClick={() => onRemoveActivity(activity.id)}>×</button></li>)}</ul><button className="add-item" onClick={onAdd}>+ Add an experience</button></div></article>; }

function StopModal({ trip, onClose, onSave }) { const [form, setForm] = useState({ city: cities[0], startDate: trip.start_date, endDate: trip.end_date, budget: "" }); const [error, setError] = useState(""); const change = (event) => setForm({ ...form, [event.target.name]: event.target.value }); function submit(event) { event.preventDefault(); if (!form.startDate || !form.endDate) return setError("Choose dates for this stop."); if (form.endDate < form.startDate) return setError("The departure must come after arrival."); onSave({ ...form, budget: Number(form.budget || 0) }); } return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={submit}><div className="modal-head"><h2>Add a stop</h2><button className="icon-btn" type="button" onClick={onClose}>×</button></div><label className="field">City<select name="city" value={form.city} onChange={change}>{cities.map((city) => <option key={city}>{city}</option>)}</select></label><div className="two-fields"><label className="field">Arrive<input name="startDate" type="date" min={trip.start_date} max={trip.end_date} value={form.startDate} onChange={change} /></label><label className="field">Leave<input name="endDate" type="date" min={form.startDate || trip.start_date} max={trip.end_date} value={form.endDate} onChange={change} /></label></div><label className="field">City budget (₹)<input name="budget" type="number" min="0" placeholder="0" value={form.budget} onChange={change} /></label>{error && <div className="alert">{error}</div>}<div className="form-actions"><button className="primary">Add to route</button><button className="secondary" type="button" onClick={onClose}>Cancel</button></div></form></div>; }

function ActivityModal({ city, onClose, onSave }) { const [form, setForm] = useState({ name: "", time: "10:00", cost: "" }); const ideas = ["Morning market walk", "Local food tasting", "Museum afternoon", "Sunset viewpoint"]; const selectIdea = (name) => setForm({ ...form, name }); return <div className="modal-backdrop" role="dialog" aria-modal="true"><form className="modal" onSubmit={(event) => { event.preventDefault(); if (form.name.trim()) onSave({ ...form, cost: Number(form.cost || 0) }); }}><div className="modal-head"><div><p className="eyebrow" style={{ marginBottom: 4 }}>{city}</p><h2>Add an experience</h2></div><button className="icon-btn" type="button" onClick={onClose}>×</button></div><div className="suggestions">{ideas.map((idea) => <button type="button" onClick={() => selectIdea(idea)} key={idea}>{idea}</button>)}</div><label className="field">Experience<input autoFocus value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. Sunset food walk" /></label><div className="two-fields"><label className="field">Time<input type="time" value={form.time} onChange={(event) => setForm({ ...form, time: event.target.value })} /></label><label className="field">Cost (₹)<input type="number" min="0" value={form.cost} onChange={(event) => setForm({ ...form, cost: event.target.value })} placeholder="0" /></label></div><div className="form-actions"><button className="primary">Add experience</button><button className="secondary" type="button" onClick={onClose}>Cancel</button></div></form></div>; }

function TripEditor({ trip, onSave, onCancel }) { const [name, setName] = useState(trip.name); const [description, setDescription] = useState(trip.description || ""); const [publicTrip, setPublicTrip] = useState(trip.is_public); const [saving, setSaving] = useState(false); async function submit(event) { event.preventDefault(); if (!name.trim()) return; setSaving(true); try { await onSave({ name, description: description || null, is_public: publicTrip }); } finally { setSaving(false); } } return <form className="form-card" style={{ marginTop: 9, maxWidth: 560 }} onSubmit={submit}><label className="field">Trip name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label style={{ display: "flex", gap: 8, alignItems: "center", fontSize: 13, marginBottom: 17 }}><input type="checkbox" checked={publicTrip} onChange={(event) => setPublicTrip(event.target.checked)} /> Share this journey publicly</label><div className="form-actions"><button className="primary" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button><button className="secondary" type="button" onClick={onCancel}>Cancel</button></div></form>; }
function fullDate(value) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "Dates TBD"; }
function money(value) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0); }
