import { useCallback, useEffect, useMemo, useState } from 'react';
import { createItem, createStop, getBudget, getTrip, listCities, listItems, listStops, shareTrip, updateStop } from '../api/trips';
import PlannerAssistant from '../components/assistant/PlannerAssistant';

const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0);
const blankStop = (trip, sequence) => ({ city_id: '', sequence, start_date: trip.start_date, end_date: trip.end_date, description: '', budget_estimate: '' });

export default function TripBuilderPage({ tripId, navigate }) {
  const [trip, setTrip] = useState(null); const [cities, setCities] = useState([]); const [stops, setStops] = useState([]); const [items, setItems] = useState({}); const [adding, setAdding] = useState(false); const [stopForm, setStopForm] = useState(null); const [error, setError] = useState(''); const [sharing, setSharing] = useState(false);
  const load = useCallback(async () => { setError(''); try { const [tripData, cityData, stopData, budget] = await Promise.all([getTrip(tripId), listCities(), listStops(tripId), getBudget(tripId)]); const itemEntries = await Promise.all(stopData.map(async (stop) => [stop.id, await listItems(tripId, stop.id)])); setTrip({ ...tripData, total_budget: budget.total_budget }); setCities(cityData); setStops(stopData); setItems(Object.fromEntries(itemEntries)); } catch (e) { setError(e.message); } }, [tripId]);
  useEffect(() => { load(); }, [load]);
  const cityById = useMemo(() => Object.fromEntries(cities.map((city) => [city.id, city])), [cities]);
  const addStop = async (event) => { event.preventDefault(); try { await createStop(tripId, { ...stopForm, budget_estimate: Number(stopForm.budget_estimate || 0) }); setAdding(false); setStopForm(null); await load(); } catch (e) { setError(e.message); } };
  const saveStop = async (stop, data) => { try { await updateStop(tripId, stop.id, { ...data, budget_estimate: Number(data.budget_estimate || 0) }); await load(); } catch (e) { setError(e.message); } };
  const addItem = async (stop, data, reset) => { try { await createItem(tripId, stop.id, { ...data, day_index: Number(data.day_index), sequence: (items[stop.id]?.filter((item) => item.day_index === Number(data.day_index)).length || 0) + 1, cost: Number(data.cost || 0), time_slot: data.time_slot || undefined, notes: data.notes || undefined }); reset(); await load(); } catch (e) { setError(e.message); } };
  const publish = async () => { setSharing(true); try { const result = await shareTrip(tripId); setTrip({ ...trip, ...result, is_public: result.is_public }); navigator.clipboard?.writeText(`${window.location.origin}/public/${tripId}`); } catch (e) { setError(e.message); } finally { setSharing(false); } };
  if (!trip) return <main className="page"><p>{error ? `Couldn’t open trip: ${error}` : 'Opening your plan…'}</p></main>;
  return <main className="page builder"><button className="back" onClick={() => navigate('/dashboard')}>← My trips</button><section className="builder-head"><div><span className="eyebrow">YOUR JOURNEY</span><h1>{trip.name}</h1><p>{trip.start_date} — {trip.end_date}</p></div><div className="budget-total"><span>LIVE TRIP BUDGET</span><strong>{money(trip.total_budget)}</strong><button className="text-button" onClick={publish} disabled={sharing}>{trip.is_public ? 'Shared ✓' : sharing ? 'Sharing…' : 'Share trip'}</button></div></section>{trip.is_public && <p className="success">Share link copied (temporary public view uses this trip ID).</p>}{error && <p className="alert">{error}</p>}<div className="builder-layout"><section><div className="section-heading"><div><h2>Your sections</h2><p className="muted">Add the cities that make up your route.</p></div><button className="button small" onClick={() => { setAdding(true); setStopForm(blankStop(trip, stops.length + 1)); }}>+ Add another section</button></div>{adding && <form className="panel stop-form" onSubmit={addStop}><h3>New section</h3><StopFields form={stopForm} setForm={setStopForm} cities={cities} /><button className="button small">Add section</button><button type="button" className="text-button" onClick={() => setAdding(false)}>Cancel</button></form>}{stops.length === 0 && !adding && <div className="empty"><h3>Start with your first destination</h3><button className="button" onClick={() => { setAdding(true); setStopForm(blankStop(trip, 1)); }}>Add a section</button></div>}{stops.map((stop) => <StopSection key={stop.id} stop={stop} city={cityById[stop.city_id]} cities={cities} items={items[stop.id] || []} onSave={saveStop} onAddItem={addItem} />)}</section><PlannerAssistant trip={trip} stops={stops} /></div></main>;
}

function StopFields({ form, setForm, cities }) { const set = (key, value) => setForm({ ...form, [key]: value }); return <div className="form-grid"><CityPicker cityId={form.city_id} cities={cities} onSelect={(cityId) => set('city_id', cityId)} /><div className="two-col"><label>Arrival<input required type="date" value={form.start_date} onChange={(e) => set('start_date', e.target.value)} /></label><label>Departure<input required type="date" min={form.start_date} value={form.end_date} onChange={(e) => set('end_date', e.target.value)} /></label></div><label>Section description<textarea value={form.description || ''} onChange={(e) => set('description', e.target.value)} /></label><label>Budget estimate<input min="0" step="0.01" type="number" value={form.budget_estimate ?? ''} onChange={(e) => set('budget_estimate', e.target.value)} /></label></div>; }
function CityPicker({ cityId, cities, onSelect }) { const selected = cities.find((city) => city.id === cityId); const [value, setValue] = useState(selected ? `${selected.name}, ${selected.country}` : ''); const optionsId = `cities-${cityId || 'new'}`; useEffect(() => { const city = cities.find((entry) => entry.id === cityId); if (city) setValue(`${city.name}, ${city.country}`); }, [cityId, cities]); const select = (next) => { setValue(next); const city = cities.find((entry) => `${entry.name}, ${entry.country}` === next); onSelect(city?.id || ''); }; return <label>Place<input required list={optionsId} placeholder="Search and choose a city…" value={value} onChange={(e) => select(e.target.value)} /><datalist id={optionsId}>{cities.map((city) => <option key={city.id} value={`${city.name}, ${city.country}`} />)}</datalist></label>; }
function StopSection({ stop, city, cities, items, onSave, onAddItem }) { const [edit, setEdit] = useState(false); const [form, setForm] = useState(stop); const [activity, setActivity] = useState({ name: '', day_index: 1, time_slot: '', cost: '', notes: '' }); const grouped = items.reduce((all, item) => ({ ...all, [item.day_index]: [...(all[item.day_index] || []), item] }), {}); return <article className="stop-section"><header><div><span className="section-number">SECTION {stop.sequence}</span><h2>{city ? `${city.name}, ${city.country}` : 'Destination'}</h2><p>{stop.start_date} — {stop.end_date}</p></div><button className="text-button" onClick={() => { setForm(stop); setEdit(!edit); }}>{edit ? 'Cancel' : 'Edit'}</button></header>{edit ? <form className="panel" onSubmit={(e) => { e.preventDefault(); onSave(stop, form); setEdit(false); }}><StopFields form={form} setForm={setForm} cities={cities} /><button className="button small">Save section</button></form> : <><p>{stop.description || 'No notes for this section yet.'}</p><p className="section-budget">Section estimate: {money(stop.budget_estimate)}</p></>}<div className="day-list">{Object.entries(grouped).map(([day, dayItems]) => <div className="day" key={day}><h3>Day {day}</h3>{dayItems.map((item) => <div className="activity" key={item.id}><span>{item.time_slot || 'Flexible'}</span><div><strong>{item.name}</strong>{item.notes && <small>{item.notes}</small>}</div><b>{money(item.cost)}</b></div>)}</div>)}</div><ItemForm onAdd={(data, reset) => onAddItem(stop, data, reset)} activity={activity} setActivity={setActivity} /></article>; }
function ItemForm({ onAdd, activity, setActivity }) { const set = (key, value) => setActivity({ ...activity, [key]: value }); const submit = (event) => { event.preventDefault(); onAdd(activity, () => setActivity({ name: '', day_index: activity.day_index, time_slot: '', cost: '', notes: '' })); }; return <form className="item-form" onSubmit={submit}><strong>Add an activity</strong><input required placeholder="Activity name" value={activity.name} onChange={(e) => set('name', e.target.value)} /><input required min="1" type="number" aria-label="Day" value={activity.day_index} onChange={(e) => set('day_index', e.target.value)} /><input placeholder="Time (e.g. 10:00)" value={activity.time_slot} onChange={(e) => set('time_slot', e.target.value)} /><input min="0" step="0.01" type="number" placeholder="Cost" value={activity.cost} onChange={(e) => set('cost', e.target.value)} /><input placeholder="Notes" value={activity.notes} onChange={(e) => set('notes', e.target.value)} /><button className="button small">Add</button></form>; }
