import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarDays, Clock3, Copy, DollarSign, Globe2, Heart, MapPin, Search, Share2, Sparkles } from "lucide-react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { catalogApi, publicApi } from "../api/app";
import { EmptyState, ErrorState, LoadingCards, PageHead } from "../components/AppShell";
import { useAuth } from "../context/AuthContext";

export function DiscoverPage() {
  const [params]=useSearchParams(); const [query,setQuery]=useState(params.get("q")||""); const [country,setCountry]=useState(""); const [category,setCategory]=useState(""); const [city,setCity]=useState(null); const qc=useQueryClient();
  const cities=useQuery({queryKey:["cities",query,country],queryFn:()=>catalogApi.cities({q:query,country,page_size:24})}); const activities=useQuery({queryKey:["activities",city?.id,category],queryFn:()=>catalogApi.activities({city_id:city?.id,category,page_size:24}),enabled:!!city}); const saved=useQuery({queryKey:["saved-cities"],queryFn:catalogApi.saved}); const savedIds=new Set(saved.data?.map(c=>c.id));
  const toggle=useMutation({mutationFn:id=>savedIds.has(id)?catalogApi.unsave(id):catalogApi.save(id),onSuccess:()=>qc.invalidateQueries({queryKey:["saved-cities"]})});
  return <><PageHead eyebrow="Destination atlas" title="Discover your next chapter" copy="Search curated cities and real activities your itinerary can actually use."/><div className="discovery-filters"><label className="search-field"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try Jaipur, Kochi, food…"/></label><select value={country} onChange={e=>setCountry(e.target.value)}><option value="">India only</option>{[...new Set(cities.data?.items?.map(c=>c.country)||[])].map(c=><option key={c}>{c}</option>)}</select></div>{cities.isLoading?<LoadingCards/>:cities.isError?<ErrorState error={cities.error}/>:<div className="destination-grid">{cities.data?.items?.map(c=><article className={`destination-card ${city?.id===c.id?"selected":""}`} onClick={()=>setCity(c)} key={c.id}><div style={{backgroundImage:`url(${c.image_url})`}}><button className={`heart-button ${savedIds.has(c.id)?"saved":""}`} onClick={e=>{e.stopPropagation();toggle.mutate(c.id)}}><Heart/></button></div><span className="eyebrow">{c.country}</span><h2>{c.name}</h2><p>{c.description||"A city worth slowing down for."}</p><small><DollarSign/> Cost index {c.cost_index} <Sparkles/> Popularity {c.popularity}</small></article>)}</div>}{city&&<section className="drawer-section"><div className="section-heading"><div><span className="eyebrow">Curated in {city.name}</span><h2>Things worth doing</h2></div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{["culture","food","nature","adventure","shopping"].map(x=><option key={x}>{x}</option>)}</select></div><div className="activity-grid">{activities.data?.items?.map(a=><article className="activity-card" key={a.id}><div style={{backgroundImage:`url(${a.image_url||city.image_url})`}}/><span className="category-pill">{a.category}</span><h3>{a.name}</h3><p>{a.description}</p><small><Clock3/>{a.duration_hours}h <DollarSign/>₹{a.cost}</small></article>)}</div></section>}</>;
}

export function CommunityPage() {
  const [q,setQ]=useState(""); const trips=useQuery({queryKey:["public-trips",q],queryFn:()=>publicApi.list({q,page_size:24})});
  return <><PageHead eyebrow="Community field notes" title="Journeys worth borrowing" copy="Explore itineraries shared by travellers—and make a private copy your own."/><div className="toolbar"><label className="search-field"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search public trips"/></label><span className="result-count">{trips.data?.total||0} shared stories</span></div>{trips.isLoading?<LoadingCards/>:trips.isError?<ErrorState error={trips.error}/>:trips.data?.items?.length?<div className="community-grid">{trips.data.items.map(t=><Link className="community-card" to={`/share/${t.share_token}`} key={t.id}><div style={{backgroundImage:`url(${t.cover_image_url||"https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=900&q=80"})`}}><span><Globe2/>Public journal</span></div><div><span className="eyebrow">{t.destination_count} destinations</span><h2>{t.name}</h2><p>{t.description||"A journey shared with the GlobeTrotter community."}</p><small><CalendarDays/>{t.start_date} → {t.end_date}</small></div></Link>)}</div>:<EmptyState title="The community journal is quiet" copy="Publish an itinerary and become the first inspiration."/>}</>;
}

export function PublicTripPage() {
  const {slug}=useParams(); const nav=useNavigate(); const {user}=useAuth(); const trip=useQuery({queryKey:["public-trip",slug],queryFn:()=>publicApi.get(slug)}); const copy=useMutation({mutationFn:()=>publicApi.copy(slug),onSuccess:t=>nav(`/trips/${t.id}/build`)});
  if(trip.isLoading)return <div className="public-loading"><span className="spinner"/>Opening shared journey…</div>; if(trip.isError)return <div className="public-error"><Globe2/><h1>This journey is unavailable</h1><p>{trip.error.message}</p><Link to="/community">Browse community</Link></div>;
  const t=trip.data; const share=()=>navigator.share?navigator.share({title:t.name,url:location.href}):navigator.clipboard.writeText(location.href);
  return <div className="public-page"><header className="public-nav"><Link className="brand" to="/"><span className="brand-mark"><Globe2/></span>GlobeTrotter</Link><div><button className="secondary-button" onClick={share}><Share2/>Share</button>{user?<button className="primary-button" onClick={()=>copy.mutate()}><Copy/>Copy trip</button>:<Link className="primary-button" to="/login">Sign in to copy</Link>}</div></header><section className="public-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(6,25,30,.9),rgba(6,25,30,.2)),url(${t.cover_image_url||"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85"})`}}><Link to="/community"><ArrowLeft/>Community</Link><span className="passport-stamp"><MapPin/> SHARED JOURNEY</span><h1>{t.name}</h1><p>{t.description}</p><div><span><CalendarDays/>{t.start_date} — {t.end_date}</span><span><MapPin/>{t.stops.length} stops</span></div></section><main className="public-itinerary"><span className="eyebrow">The route</span><h2>Day by day</h2>{t.stops.map((s,i)=><section className="public-stop" key={s.id}><div className="stop-number">{i+1}</div><div><h3>{s.city?.name}, {s.city?.country}</h3><p>{s.start_date} — {s.end_date}</p><div className="public-items">{s.items.map(x=><article key={x.id}><span>{x.time_slot||`Day ${x.day_index}`}</span><strong>{x.name}</strong><small>{x.notes}</small></article>)}</div></div></section>)}</main><footer className="public-footer"><Globe2/><strong>Plan beautifully. Travel freely.</strong><Link to="/signup">Create your own journey</Link></footer></div>;
}


