import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Check, Globe2, Mail, MapPin, ShieldCheck, Sparkles, UserRound, Users } from "lucide-react";
import { adminApi, authApi, catalogApi } from "../api/app";
import { useAuth } from "../context/AuthContext";
import { useTheme } from "../context/ThemeContext";
import { ErrorState, LoadingCards, PageHead } from "../components/AppShell";

export function ProfilePage() {
  const {user,updateUser}=useAuth(); const {theme,toggle}=useTheme(); const [saved,setSaved]=useState(false); const cities=useQuery({queryKey:["saved-cities"],queryFn:catalogApi.saved}); const [form,setForm]=useState({...user});
  const save=useMutation({mutationFn:()=>authApi.update({first_name:form.first_name,last_name:form.last_name,phone:form.phone||null,city:form.city||null,country:form.country||null,language:form.language}),onSuccess:u=>{updateUser(u);setSaved(true);setTimeout(()=>setSaved(false),1800)}});
  return <><PageHead eyebrow="Traveller profile" title="Make GlobeTrotter yours" copy="Your details, preferences and saved places in one calm corner."/><div className="profile-grid"><section className="panel profile-summary"><div className="profile-avatar">{(user.first_name?.[0]||"G")+(user.last_name?.[0]||"T")}</div><h2>{user.first_name} {user.last_name}</h2><p><Mail/>{user.email}</p><p><MapPin/>{user.city||"Add your home city"}{user.country&&`, ${user.country}`}</p>{user.is_admin&&<span className="admin-badge"><ShieldCheck/>Administrator</span>}</section><form className="panel profile-form" onSubmit={e=>{e.preventDefault();save.mutate()}}><div className="section-heading"><div><span className="eyebrow">Personal details</span><h2>About you</h2></div></div><div className="form-row"><label>First name<input value={form.first_name||""} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input value={form.last_name||""} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div><label>Phone<input value={form.phone||""} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="form-row"><label>City<input value={form.city||""} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Country<input value={form.country||""} onChange={e=>setForm({...form,country:e.target.value})}/></label></div><label>Language<select value={form.language||"en"} onChange={e=>setForm({...form,language:e.target.value})}><option value="en">English</option><option value="hi">Hindi</option><option value="fr">French</option><option value="es">Spanish</option></select></label><button className="primary-button" disabled={save.isPending}>{saved?<><Check/>Saved</>:"Save changes"}</button></form><section className="panel preferences-panel"><div className="section-heading"><div><span className="eyebrow">Appearance</span><h2>Journal theme</h2></div></div><button className="theme-preview" onClick={toggle}><span className={theme}/><div><strong>{theme==="dark"?"Ink blue night":"Warm sand daylight"}</strong><small>Tap to switch theme</small></div></button><div className="section-heading saved-heading"><div><span className="eyebrow">Wish list</span><h2>Saved cities</h2></div></div><div className="saved-tags">{cities.data?.length?cities.data.map(c=><span key={c.id}><Globe2/>{c.name}</span>):<p>Heart destinations in Discover to save them here.</p>}</div></section></div></>;
}

export function AdminPage() {
  const qc=useQueryClient(); const analytics=useQuery({queryKey:["admin-analytics"],queryFn:adminApi.analytics}); const users=useQuery({queryKey:["admin-users"],queryFn:()=>adminApi.users({page_size:50})}); const update=useMutation({mutationFn:({id,body})=>adminApi.updateUser(id,body),onSuccess:()=>qc.invalidateQueries({queryKey:["admin-users"]})});
  if(analytics.isLoading||users.isLoading)return <LoadingCards/>; if(analytics.isError||users.isError)return <ErrorState error={analytics.error||users.error}/>; const a=analytics.data; const metrics=[["Travellers",a.totals.users,Users],["Journeys",a.totals.trips,Globe2],["Public trips",a.totals.public_trips,Sparkles],["AI proposals",a.totals.ai_proposals,ShieldCheck]];
  return <><PageHead eyebrow="GlobeTrotter control room" title="Admin dashboard" copy="A clear view of community growth, catalog use and AI planning."/><div className="metrics-grid">{metrics.map(([label,value,Icon])=><div className="metric-card" key={label}><Icon/><span>{label}</span><strong>{value}</strong></div>)}</div><div className="admin-grid"><section className="panel chart-panel"><div className="section-heading"><div><span className="eyebrow">Popular routes</span><h2>Most visited cities</h2></div></div><ResponsiveContainer width="100%" height={280}><BarChart data={a.popular_cities}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" fill="#0d766e" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Planner reliability</span><h2>AI source usage</h2></div></div><div className="source-stats">{Object.entries(a.ai_sources).map(([source,count])=><div key={source}><span className="ai-orb"><Sparkles/></span><p><strong>{source==="gemini"?"Gemini":"Deterministic rules"}</strong><small>{source==="gemini"?"Creative plans validated by rules":"Reliable automatic fallback"}</small></p><b>{count}</b></div>)}</div></section></div><section className="panel user-table-panel"><div className="section-heading"><div><span className="eyebrow">Account management</span><h2>Travellers</h2></div><span>{users.data.total} total</span></div><div className="table-scroll"><table><thead><tr><th>Traveller</th><th>Location</th><th>Role</th><th>Status</th><th>Controls</th></tr></thead><tbody>{users.data.items.map(u=><tr key={u.id}><td><strong>{u.first_name} {u.last_name}</strong><small>{u.email}</small></td><td>{u.city||"—"}{u.country&&`, ${u.country}`}</td><td>{u.is_admin?"Admin":"Traveller"}</td><td><span className={u.is_active?"status active":"status"}>{u.is_active?"Active":"Disabled"}</span></td><td><button className="secondary-button compact" onClick={()=>update.mutate({id:u.id,body:{is_active:!u.is_active}})}>{u.is_active?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div></section></>;
}
